# Configure generation of web page(s).
name: OpenSSF Global Cyber Policy Working Group
# Don't insert the name of the repo at the beginning
# https://stackoverflow.com/questions/46375765/how-do-you-remove-header-on-github-pages
title: OpenSSF Global Cyber Policy Working Group
kramdown:
  # See: https://dieghernan.github.io/chulapa-101/cheatsheets/02-kramdown-cheat-sheet
  toc_levels: 2..6
#
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Note: We specific *specific* scopes in documents that were directly
# published and referenced on GitHub. That way we don't need to add YAML
# to the beginning of the markdown in those cases.
# In newer markdown documents, use a yaml prefix to set "description", etc.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Open Source Security Foundation (OpenSSF)
  -
    scope:
      path: "CRA*"
    values:
      description: This is collection of documents and information related to the European Union's Cyber Resiliance Act.
